### ISSUE TITLE
'GO Central' still remains in various files

### ISSUE THREAD

**Issue by cmungall** [geneontology/touchup#10]
As report by Harold in the MGI GAF file

I looked briefly; if we look at:
http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/paint/

Most have timestamp jenkins/touchup, 2 weeks ago

Some have a more recent timestamp, e.g. 
http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/paint/PTHR12566/

So maybe pgaudet overwrote the touchup file?

**Comment by krchristie** [comment]
For PTHR12566, Pascale committed new annotations by Marc, so looks like this was a new directory, not something that had ever been committed by the touchup script.

Might be worth looking at what PAINT writes in GAF files.

**Comment by hdrabkin** [comment]
I assumed something ( script, human?) takes data in all of the  family gafs and parses them out into the taxon-specific gafs?
If so, I can see how this might add annotations still using "GO Central" to a file that now doesn't have them (uses GO_Central)?
--
Harold

**Comment by cmungall** [comment]
@krchristie - thanks, I didn't spot that, I assumed it was an overwrite.

OK, so it looks like this may be temporary, the incorrect value leaked in from an earlier iteration.

@hdrabkin - yes, the MOD GAFs are aggregated from the per-family annotations. I think we should fix the pipeline so that touchup always runs prior to the aggregation step, but I'd rather coordinate with @selewis on this when she is back from biocurator.

How urgent is this?

**Comment by doughowe** [comment]
No urgency from our end.  We just substitute "GO Central" for "GO_Central" on our GAF before we submit it.

**Comment by krchristie** [comment]
Since I just finished a family in PAINT, I checked what is being written by Paint version 1.13, and it is writing species specific GAFs with "GO Central".

bash-3.2$ grep -c "GO Central" PTHR16517.gaf 
769
bash-3.2$ grep -c "GO_Central" PTHR16517.gaf 
0

**Comment by cmungall** [comment]
OK this is not great. I guess for now just do a 

```
perl -npe 's/GO Central/GO_Central/' PTHR16517.gaf  > PTHR16517-fixed.gaf 
diff PTHR16517.gaf PTHR16517-fixed.gaf 
mv PTHR16517-fixed.gaf  PTHR16517.gaf 
```

til everyone is back from China

**Comment by krchristie** [comment]
done for PTHR16517.gaf, will do this for any other families I commit until this is fixed.
