### ISSUE TITLE
Transfer this repo to geneontology org

### ISSUE THREAD

**Issue by cmungall** [geneontology/touchup#11]
Click "settings" on bottom right

Should be placed here:
https://github.com/geneontology

Note: no need to explicitly redirect or even re-check out, gh handles the redirect for you perfectly

After that we should set up teams

**Comment by monicacecilia** [comment]
@cmungall I think you should "assign" this to @selewis, and send some smoke signals, else I doubt she will see it in an ocean of email from the last week.

**Comment by cmungall** [comment]
I don't have rights to either transfer or assign in this repo!

**Comment by monicacecilia** [comment]
neither do I... :worried:

**Comment by selewis** [comment]
Apparently neither do I.

We'll have to sort it out by Skype over the weekend, or what until Monday.

**Comment by kltm** [comment]
@selewis this is your repo--you are the only one who can transfer it. Logged in, try:

https://github.com/selewis/touchup/settings

There should be an option near the bottom for "Transfer ownership". You'll need to type in the name of your repo again, and then "geneontology" for the new owner.

More information here: https://help.github.com/articles/transferring-a-repository/

**Comment by selewis** [comment]
done (thanks Seth for interpreting the UI for me)
