### ISSUE TITLE
PAINT needs to treat IKRs coming from sources other than GO_Central need to be treated as other EXP annotations

### ISSUE THREAD

**Issue by pgaudet** [geneontology/touchup#18]
I hope this issue makes sense ! 

See PTHR16677 for an example - Q30201 has 'not' to 'antigen binding', but when I propagate it fails to propagate the NOT. The behavior should be the same as for EXP (such as IDA) annotations). 
Thanks, 

Pascale

**Comment by selewis** [comment]
I assume you mean PTHR16675. I am hoping this is the same bug as #16 (which I just fixed). It had to do with two genes: one protein which led to dropping a not. 

But am double checking.

**Comment by selewis** [comment]
You're re-annotating aren't you? Failed to understand that. Still pursuing...

**Comment by pgaudet** [comment]
Hi Suzi, 

The family in indeed PTHR16675. 
The annotation I was talking about in the issue is not in PAINT anymore; however it's in protein2GO.


But when I take a NOT annotation by IDA with a PMID, I just cannot propagate it. I tried to make a screenshot - it it's not loading I'll email it. 
![not-not_propagted](https://cloud.githubusercontent.com/assets/4782928/9224838/d171013e-4105-11e5-9928-9b38cd7175d1.png)


Thanks, 

Pascale

**Comment by pgaudet** [comment]
This is now working. I can propagate all the NOTs in this tree. 

Thanks :) 
Pascale
