### ISSUE TITLE
Loaded PAINT annotations appear to be incorrect

### ISSUE THREAD

**Issue by kltm** [geneontology/touchup#23]
Okay, so the issue is data: the loaded PAINT file contains annotations that should actually be represented in another GAF. While the effects are seen in AmiGO, this is actually an upstream data issue, yes? Tagging on @cmungall and @selewis to try and figure out what exactly is happening here.

The initial thread is here: geneontology/amigo#253. Possibly porting over here on @cmungall recommendation.

If it's accepted here, I'll close the amigo issue.

**Comment by cmungall** [comment]
This line in software/utilities/paint-gaf-filter.pl

	    $organism{'taxon:284812'} = { 'name' => 'pombase', 'lines' => [] };

Previously pombase were using the strain ID. Now they use the species 
ID.


  is_a NCBITaxon:131567 ! cellular organisms
    is_a NCBITaxon:2759 ! Eukaryota
     is_a NCBITaxon:33154 ! Opisthokonta
      is_a NCBITaxon:4751 ! Fungi
       is_a NCBITaxon:451864 ! Dikarya
        is_a NCBITaxon:4890 ! Ascomycota
         is_a NCBITaxon:451866 ! Taphrinomycotina
          is_a NCBITaxon:147554 ! Schizosaccharomycetes
           is_a NCBITaxon:34346 ! Schizosaccharomycetales
            is_a NCBITaxon:4894 ! Schizosaccharomycetaceae
             is_a NCBITaxon:4895 ! Schizosaccharomyces
              is_a NCBITaxon:4896 ! Schizosaccharomyces pombe  <- 
SPECIES, USE THIS
               is_a NCBITaxon:284812 ! Schizosaccharomyces pombe 972h-  
<- STRAIN

**Comment by selewis** [comment]
So I made the change to the Perl script.
Next question is when/how can we get this job under Jenkins (before Heiko departs!)

**Comment by selewis** [comment]
Much of the cleanup depends on when touchup can next be run so that this (and a raft of other problems, such as the doppelgangers) can be remedied

**Comment by pgaudet** [comment]
It says there is a question here, but what is it ?
