### ISSUE TITLE
IRD NOT is incorrectly propagated to leaf sequences with IBA

### ISSUE THREAD

**Issue by huaiyumi** [geneontology/touchup#26]
When a PTN has a NOT annotation with IRD evidence code, the NOT is propagated to all the leaf sequences with IBA. Example: PTHR10663:PTN000070946 to GO:0005802 and GO:0016192.

PANTHER PTN000070946    PTN000070946    NOT     GO:0005802      PAINT_REF:10663 IRD     PANTHER:PTN000838827    C                       protein taxon:33213     20120409        GO_Central              
PANTHER PTN000070946    PTN000070946    NOT     GO:0016192      PAINT_REF:10663 IRD     PANTHER:PTN000838827    P                       protein taxon:33213     20120409        GO_Central              
ENSEMBL ENSG00000156011 PSD3    NOT     GO:0005802      PAINT_REF:10663 IBA     PANTHER:PTN000070946    C       PH and SEC7 domain-containing protein 3 UniProtKB:Q9NYI0|PTN000070965|ENSG00000156011|PSD3_HUMAN|EFA6R|HCA67|KIAA0942   protein taxon:9606      20120409        GO_Central              
ENSEMBL ENSG00000156011 PSD3    NOT     GO:0016192      PAINT_REF:10663 IBA     PANTHER:PTN000070946    P       PH and SEC7 domain-containing protein 3 UniProtKB:Q9NYI0|PTN000070965|ENSG00000156011|PSD3_HUMAN|EFA6R|HCA67|KIAA0942   protein taxon:9606      20120409        GO_Central              
ENSEMBL ENSPTRG00000020031      ENSG00000156011 NOT     GO:0005802      PAINT_REF:10663 IBA     PANTHER:PTN000070946    C               UniProtKB:H2R115|PTN000070959|ENSPTRG00000020031        protein taxon:9598      20120409        GO_Central              
ENSEMBL ENSPTRG00000020031      ENSG00000156011 NOT     GO:0016192      PAINT_REF:10663 IBA     PANTHER:PTN000070946    P               UniProtKB:H2R115|PTN000070959|ENSPTRG00000020031        protein taxon:9598      20120409        GO_Central

**Comment by selewis** [comment]
Are you and Pascale now both watching this list? Hope so. That way we can discuss these.

**Comment by huaiyumi** [comment]
I do now.

**Comment by selewis** [comment]
super

**Comment by selewis** [comment]
This is the same as issue #19
