### ISSUE TITLE
Qualifiers are not loaded in PAINT2.0

### ISSUE THREAD

**Issue by huaiyumi** [geneontology/touchup#28]
Qualifiers for experimental annotations are not loaded when a tree is open with PAINT2.0. They are loaded correctly with PAINT1.14.

Examples:
NOT 	test family: PTHR13038	
	Q7Z3C6 (Human ATG9A) has an experimental NOT annotation to autophagosome membrane (GO:0000421) 	
		
COLOCALIZES_WITH	test family PTHR120607	
	Human APC2 (O95996) annotated to 'colocalizes_with' cytoplasmic microtubule (GO:0005881)	
		
CONTRIBUTES_TO	test family: PTHR10050	
	Drosophila FBgn0086368 (Q9W5D4) annotated to 'contributes to 'dolichyl-phosphate-mannose-protein mannosyltransferase activity' (GO:0004169)

**Comment by selewis** [comment]
I assume you meant PTHR12607...
Lovely set of test families for these
Heiko fix the bug - I'll have 2.0.b11 out to you shortly

**Comment by huaiyumi** [comment]
Suzi, you are correct, PTHR12607.

**Comment by selewis** [comment]
Try the latest version in dropbox. The fixes were 2-fold, one a genuine bug and the other was server issues. Will have to redo when production server becomes stable.

If it works for all three then close the issue
