### ISSUE TITLE
Title bar in PAINT 2.0

### ISSUE THREAD

**Issue by huaiyumi** [geneontology/touchup#29]
The title bar in PAINT 2.0 no longer display family name. 
It would be nice to have the family name, PTHR id, and the PAINT version in the title bar. See attached image file.
![paint-title_bar](https://cloud.githubusercontent.com/assets/6653552/10985639/d942dcb0-83d7-11e5-946e-6bb9bab74c17.png)

**Comment by selewis** [comment]
I don't consider that the family name, but rather the family description. 
In any case, trivial to add

**Comment by krchristie** [comment]
Personally, I'd prefer if the family ID, e.g. PTHR10829 came first, before the family description, so that the family ID is always in the same location. The description can be useful, but sometimes not at all, like when it's just FAMILY NOT NAMED.

-Karen

**Comment by selewis** [comment]
I tend to agree with Karen on this. And if it is "FAMILY NOT NAMED" that
can just be hidden.

**Comment by huaiyumi** [comment]
As long as those information is there, it doesn't matter how you order it.
Also, if it requires extra coding to hide the "family not named", I don't think it is worth doing it.

**Comment by krchristie** [comment]
I agree with Huaiyu that it isn't worth taking extra effort to hide the description when it is "FAMILY NOT NAMED".

**Comment by selewis** [comment]
Added to the frame title
