### ISSUE TITLE
IBD annotations to terms and their parents should be saved in the PAINT GAF

### ISSUE THREAD

**Issue by pgaudet** [geneontology/touchup#30]
When a curator does an annotation to a term and to its parents, both IBD annotations should be saved to the GAF. 
The propagation to IBA then should filter any redundancy. 

The reasons for doing this are
1. For NOT annotations, we may want to say 'this protein has lost its Ser/Thr protein kinase activity but is still a protein kinase. If we annotate both the term and its parent, we can put a NOT on the more specific term and still keep the parent
2. For positive annotations, keeping annotations to terms and their parents allow to keep annotations to more general terms if primary annotations to more specific terms get deleted. 

Thanks, 
Pascale

**Comment by huaiyumi** [comment]
This is related to disabling prevention.

**Comment by selewis** [comment]
I'm not understanding what you're saying. Curators only can do things one at a time. For a positive annotation (i.e. this node/protein has this term) they can only drop on one node. Thus only one node gets an IBD and all the descendants get IBA. 

Give me a family and the term and the ancestral node please and walk this through the steps you've made

**Comment by pgaudet** [comment]
Check Issue #33 - if we can do that, maybe we can drop this issue here.

**Comment by pgaudet** [comment]
Yes, this works too. Tested this with PTHR10006, annotated both 'cell adhesion' and 'negative regulation of cell adhesion mediated by integrin', and the GAF file has both terms.
