### ISSUE TITLE
NOT annotation is not migrated when a PTN is moved to a new family

### ISSUE THREAD

**Issue by huaiyumi** [geneontology/touchup#32]
Here is an example.
PTN000666984 in PTHR24259 of v.9.0 has an IKR NOT annotation to "serine-type endopeptidase activity (GO:0004252)", because its ancestor node PTN001207690 has the annotation to the term.
![screen shot 2015-11-06 at 1 41 00 pm](https://cloud.githubusercontent.com/assets/6653552/11009489/1bb27e84-848c-11e5-8da7-5e6650b20248.png)

PTNR24259 is merged to PTHR24256 in v.10. One of its ancestor node (PTN001207579) in the new tree has the annotation to the same term "serine-type endopeptidase activity (GO:0004252)", but the IKR NOT to PTN000666984 is not migrated. Therefore, PTN000666984 has an IBA to the term "serine-type endopeptidase activity (GO:0004252)". This will lead to the incorrect IBAs to all its leaf sequences.
![screen shot 2015-11-06 at 1 41 55 pm](https://cloud.githubusercontent.com/assets/6653552/11009497/32651e16-848c-11e5-895c-35e53461bbb2.png)

To fix this, all annotations to its ancestors should be checked. If any of them has the positive annotation to the term that would have resulted in a positive annotation to the migrated node, the NOT should be preserved, and the new ancestor node PTN should be used in the "with" column. Otherwise, the NOT should be dropped and logged in the "second gaf file" (the one with all the IBD annotation excluded by the touch up script).

**Comment by selewis** [comment]
That was the intent. Thought is was working like this. Will check on this family

**Comment by selewis** [comment]
In latest liftover (with duplicated notes) the NOT is appearing correctly for node PTN000666984 in family PTHR24256.
