### ISSUE TITLE
Violation of taxon constraints should give a warning with a pop up box of choices of actions

### ISSUE THREAD

**Issue by pgaudet** [geneontology/touchup#34]
Violation of taxon constraints should give a warning with a pop up box of choices of actions. 

The message in pop up box should be 'Taxon constraint violated [insert what is the constraint that failed, e.g. only_in eukaryotes]; do you wish to proceed ? ' 

Choices are: 
1. Yes - Ignore taxon constraints (this will proceed with what the curator wanted to do) 
2.  No - Cancel operation (this will stop the current annotation) 

Other points: 
- Only the *node* the curator is attempting to annotate should be checked, not the descendants. 
- Taxon violations for IBA annotations should be checked separately. We suggest to not do this now and discuss it separately, as this aspect is not a showstopper.

**Comment by selewis** [comment]
Actually three choices
1. Ignore (and record the challenges)
2. Cancel
3. Proceed and automatically add NOTs at taxa where loss of function occurred.

**Comment by pgaudet** [comment]
Hello, 

I just saw Taxon constraints in action in PAINT 2.22 ! I annotated PTN000777450 with GO:0019146 (arabinose-5-phosphate isomerase activity), which is 'ONLY IN BACTERIA', and PAINT added NOT annotations on the 2 eukaryotes present in that clade. 

I wanted to report that the implementation is not according to the specs: there is no notifications (although one does see the NOTs). We should just look at whether we understand the behavior, and document it in the PAINT manual. 

A nice additional feature would be that the Evidence Table would record the NOT, indicationg a taxon violation. 

Thanks ! Pascale

**Comment by selewis** [comment]
Did you look at the balloon notification? The text with the yellow
background when you hover over the node? If a dialog were to popup then the
drag&drop operation would be over, so had to add the notice in the balloon
text. For debugging need you to confirm whether or not the notification did
show up there.

-S
