### ISSUE TITLE
Check that all qualifiers got migrated during PAINT 9 to 10 update

### ISSUE THREAD

**Issue by pgaudet** [geneontology/touchup#35]

**Comment by selewis** [comment]
Nothing gets (or has gotten) migrated until touchup runs - but when it does we should check.

If you open an existing paint gaf from paint 9 in 2.0 (and plan to save it) then be careful.

**Comment by selewis** [comment]
Also any ideas on how to check this? Too much to eyeball them all. Counts from random greps could be misleading. This needs more discussion for assessing, a method that is relatively simple. Have some thoughts, but it's really several different things that the same symptom may be caused by.

**Comment by pgaudet** [comment]
I will look for specific examples. What do you think ?

**Comment by selewis** [comment]
Yes please do. Need things to test against.

**Comment by selewis** [comment]
Same as issue #28
