### ISSUE TITLE
Empty gaf file when it's been viewed

### ISSUE THREAD

**Issue by selewis** [geneontology/touchup#37]
change the code to spit out a gaf file even if there are no annotations to indicate we looked at it on a certain date

**Comment by krchristie** [comment]
Do you mean that PAINT should generate a gaf file even when there are no annotations?

It seems to me that it does. The file contains only a header line, but the gaf file is generated.

> bash-3.2$ more PTHR39415.gaf 
> !gaf-version: 2.0

At the PAINT Jamboree last year, we agreed to commit only the .txt file in the situation where a family has been examined, but no annotations were propagated, and the PAINT User Guide reflects that. 

However, I recently commited a number of these, and it is kind of annoying to commit only the *.txt file as if I commit only that, I either end up with a bunch of files unrecognized by the "svn status" command, or have to manually remove those 8 other files. 

So, for simplicity, I think it is better to just commit all 9 files, including the 1 line *.gaf file. The one I listed above has been committed to svn.

**Comment by selewis** [comment]
The curator will still need to actively 'save' the file, but given they do that then the GAF file will be saved.
I don't see any point to only committing the .txt file. It doesn't hurt to include the others in the commit in any way. So a) Save if you've looked at it, even if no annotations were made and b) just commit as you normally would.
