### ISSUE TITLE
duplicate notes when splitting families

### ISSUE THREAD

**Issue by krchristie** [geneontology/touchup#38]
Hi,

PTHR23431 - FAMILY NOT NAMED (76 sequences) is listed in the PAINT family nodes statistics spreadsheet with the note "GAF file only".

This family used to be part of PTHR23413, which was 60S RIBOSOMAL PROTEIN L32 AND DNA-DIRECTED RNA POLYMERASE II, SUBUNIT N when I committed it in November 2013. Now that it has been split, the notes I wrote for the family, including all the parts about the RNAP II clade, are associated only with the original family PTHR23413, while the new family for the RPB10 subunit of RNAP II has now lost those notes. 

ACTION ITEM: At the 11/17/15 PAINT call, we agreed that it would be better to duplicate the notes file for both families so that information the curator attached to the family is not lost for either the original or new family resulting from the split.

-Karen

**Comment by pgaudet** [comment]
How many families get split ? It seems this should be a case for manual review. The notes would be very confusing if they referred to nodes that are not part of that family anymore. 

- Pascale

**Comment by krchristie** [comment]
We discussed this at the meeting we just had. It's unfortunate you were having problems connecting Pascale. 

We all agreed that these families should be flagged for manual review. However, the current situation is that the original family has the notes file that contains sections that are no longer relevant, and the portion of the tree that was split into a new family has no notes at all. At the meeting, we felt that duplicating the notes so that both the original and the new families are associated with the original note is the best automatic option. 

Next, BOTH families should get flagged for manual review. Currently, the original family, PTHR23413 - 60S RIBOSOMAL PROTEIN L32 AND DNA-DIRECTED RNA POLYMERASE II, SUBUNIT N, is associated with the original notes file which contains a lot of information that is no longer relevant, so the notes file should get edited for this family, as well as for the new family.

-Karen

**Comment by selewis** [comment]
The duplicated notes are now there. The list of families (48 of them) for manual review are:
PTHR10078	PTHR11177	PTHR13479	PTHR16516	PTHR23065	PTHR23502	PTHR24089	PTHR24369    PTHR10459	PTHR11485	PTHR13992	PTHR19303	PTHR23327	PTHR23503	PTHR24173	PTHR24375    PTHR10489	PTHR12112	PTHR15071	PTHR19957	PTHR23389	PTHR23505	PTHR24198	PTHR24409
PTHR10632	PTHR12231	PTHR15282	PTHR21148	PTHR23431	PTHR23515	PTHR24242	PTHR26392    PTHR10699	PTHR12565	PTHR15505	PTHR22840	PTHR23500	PTHR24012	PTHR24256	PTHR27000    PTHR10799	PTHR13430	PTHR16515	PTHR22884	PTHR23501	PTHR24078	PTHR24361	PTHR27003
