### ISSUE TITLE
invalid sources ("RefGenome" & "GO Central") from PAINT

### ISSUE THREAD

**Issue by krchristie** [geneontology/touchup#39]
Hi,

**"RefGenome" source**
Since the recent rollback of the touchup script to the previous manually committed version of the files, we have undone some previous fixes. Specifically, this rollback unfixed the previous fix of the now obsolete "RefGenome" source.

Here is a sample svn log of the last two log entries for four of the five families (PTHR10000, PTHR10003, PTHR10005, PTHR10012, PTHR10013) I've checked (PTHR10003 had an additional entry indicating reannotation by Pascale in between these two entries by suzi):

> bash-3.2$ svn log PTHR10013/PTHR10013.gaf
> ------------------------------------------------------------------------
> r29623 | suzi | 2015-11-06 20:19:03 -0800 (Fri, 06 Nov 2015) | 3 lines
>
> Rollback of accidently committed touchup run
>
>
> ------------------------------------------------------------------------
> r29057 | suzi | 2015-10-06 09:43:15 -0700 (Tue, 06 Oct 2015) | 2 lines
>
> Revised families for PANTHERv10

MGI's specific PAINT GAF has > 1400 annotations that fail to load due to this source.

**"GO Central" source**
We also still have a large number of "GO Central" (with a space instead of an underscore) sources. Commits using PAINT-beta13 generated this source. Commits from PAINT-beta14 generate the correct "GO_Central" source.

While Harold and I originally reported this a couple months ago or so, it has not yet been fixed either. 

MGI's specific PAINT GAF has > 4000 annotations that fail to load due to this source.

thanks,

-Karen

@tberardini

**Comment by selewis** [comment]
Should be gone now. They are no longer in the paint/pre-submission directory.

**Comment by pgaudet** [comment]
These are still in the GAF file, See issue #44 for examples. Unless (1) the script that generates the pre-submission directory now does this and (2) no users that consume the GAFS (I only know of Pantree) parses the source (to check with Anushya).
