### ISSUE TITLE
Create directory automatically with family name

### ISSUE THREAD

**Issue by selewis** [geneontology/touchup#43]
And fill in family name when creating new directory

**Comment by selewis** [comment]
Added this feature to v2.16

**Comment by pgaudet** [comment]
Hello, 

This works for Marc on his PC but it's not working on my mac. 
Moreover, it saves the files in whatever previous directory you saved to, so I accidentally saved in the wrong dircectory a few times. Could it save to /mydocuments or /documents ? Or even better, allow us to specify a default directory ? 

Thanks, Pascale

**Comment by krchristie** [comment]
This works for me on a mac.

The fact that it saves files to whatever previous directory was saved to seems like normal behavior for macs. Most of the other programs that remember what directory I was in behave exactly the same way.

I prefer the current behavior over saving to /mydocuments or /documents.

thanks,

-Karen
