### ISSUE TITLE
Correct Sources for RefGenome and GO Central

### ISSUE THREAD

**Issue by pgaudet** [geneontology/touchup#44]
Hello, 
After the roll back of Nov 7, 2015 (Revision 29623), there are 67 families with "RefGenome" as the source in the GAF file, and 348 with "GO Central"

Examples: 
- RefGenome: PTHR10005
- GO Central: PTHR10552

These need to be changed to GO_Central. 

Thanks, Pascale

**Comment by selewis** [comment]
This is the kind of thing that touchup does. Once touchup is finished these will all disappear.
By the way, this is not a 'showstopper' from the perspective of PAINT. It's a showstopper for downstream consumers.
