### ISSUE TITLE
If a PTN node looses annotations, provide protein ID for that former annotation 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/touchup#47]
Example: 
NOW: 
20150630: PTN001590085 can not support previous annotation to programmed cell death (GO:0012501)

ADD protein ID: 
20150630: PTN001590085 can not support previous annotation to programmed cell death (GO:0012501) supported by UniProtKB:P12345 | UniProtKB:P99999

**Comment by selewis** [comment]
Added this feature to PAINT v2.16
