### ISSUE TITLE
Taxon checks deactivated ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/touchup#51]
Hello, 

I am annotating PTHR11136 and I accidentally annotated the root of the tree with mitochondrion. Shouldn't this be forbidden ? 

I have not yet seen the taxon constraints work as described here: 
https://github.com/geneontology/touchup/issues/34
Suzi you don't happen to have the example with which you tested this ? 

Thanks, 
Pascale

**Comment by selewis** [comment]
I had a long conversation with Chris on how the taxon ontology is actually organized and it was different that I had imagined, and actually much better as far as we're concerned.

Basically if any of the descendants may have a function (or be part of a process, or be found in a cell) then the annotation is allowable. If a particular branch has loss that capability then the "not found in" tag is added directly at that point. In light of this the PAINT+touchup code now allows these, but it should have also automatically annotated the loss at the bacteria clade (PTN000124089).

So this was a big omission on my part. I wrote the code, tested the code, and was calling the code, but only when the GAFs were first loaded! I forgot to add the call for when annotations were being carried out live by a curator. Big red face - but look for this in v2.20
